#Makefile para compilar el Cliente
#Creado por: Marco Elizalde
#Fecha: 4 de mayo del 2012

all: 
	g++ -o ssc32control `pkg-config --cflags playerc++` simple_client.cc `pkg-config --libs playerc++`

clean: 
	rm ssc32control
