#Makefile para compilar el Cliente
#Creado por: Marco Elizalde
#Fecha: 4 de mayo del 2012
#Para compilar el programa, se ejecuta en una terminal el siguiente comando:
# make

all: 
	g++ -o brazo_robotico `pkg-config --cflags playerc++` brazo_robotico.cc `pkg-config --libs playerc++`

clean: 
	rm brazo_robotico
